name: instagram_app_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  hooks_riverpod: ^2.4.10
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.15.4
  uuid: ^4.3.3
  font_awesome_flutter: ^10.7.0
  flutter_facebook_auth: ^6.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  image: ^4.1.7
  flutter_hooks: ^0.20.5
  collection: ^1.18.0
  intl: ^0.19.0
  video_thumbnail: ^0.5.3
  video_player: ^2.8.2
  lottie: ^3.0.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.4
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

